### ISSUE TITLE
Add arXiv Code & Data links

### ISSUE THREAD

**Issue by matthewfeickert** [rikab/GaussianAnsatz#1]
:wave: Hi and [nice paper](https://arxiv.org/abs/2205.03413). :+1: I was happy to see that in addition to referencing the GitHub repo for the code in the text you additionally link it in the arXiv comments

> 7 pages, 1 figure, 1 table, code available at [this https URL](https://github.com/rikab/GaussianAnsatz)

What would be even nicer is if you linked it in the "Code & Data" tab on arXiv so that it would additionally get registered in [PapersWithCode](https://paperswithcode.com/).

If you've done this before, ignore the rest of the Issue, but if you haven't you can do this from your arXiv account by logging in and then clicking on the "Link code & data" icon next to the paper submission, as demoed below in this image from arXiv's [2020-10-08 blog post on the arXivLabs feature](https://blog.arxiv.org/2020/10/08/new-arxivlabs-feature-provides-instant-access-to-code/)

![blog](https://cpb-us-e1.wpmucdn.com/blogs.cornell.edu/dist/8/7752/files/2020/10/Screen-Shot-2020-10-07-at-1.35.57-PM-1024x290.png)

**Comment by rikab** [comment]
Done!
